name: 'Setup ImageMagick compiled from sorce'
author: 'Gullit Miranda'
description: |-
  Download custom dependencies and compile ImageMagick from source to enable the custom dependencies.
  This will add extra ImageMagick bins to the $PATH

inputs:
  version:
    required: true
    description: 'ImageMagick version. See all versions available at http://www.imagemagick.org/download/releases'
    # default: 'default value if applicable'

  configure_args:
    required: false
    description: 'Extra arguments to ./configure command'
    default: '--with-gslib=yes'

runs:
  using: 'node12'
  main: 'dist/index.js'
