name: 'Setup ImageMagick compiled from sorce'
author: 'Gullit Miranda'
description: |-
  Download custom dependencies and compile ImageMagick from source to enable the custom dependencies.
  This will add extra ImageMagick bins to the $PATH

inputs:
  imagemagick_version: # change this
    required: true
    description: 'ImageMagick version'
    # default: 'default value if applicable'

runs:
  using: 'node12'
  main: 'dist/index.js'
