name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - wip
      - 'releases/*'

jobs:
  # debug:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - run: echo $PATH
  #     - run: which -a convert
  #     - run: convert --version

  # make sure build/ci work properly
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: |
  #         npm install
  #     # - run: |
  #     #     npm run build
  #     #     npm run package
  #     - run: |
  #         npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo $PATH
      - run: which -a convert
      - run: convert --version

      - uses: ./
        with:
          imagemagick_version: 6.7.7-10

      - run: echo $PATH
      - run: which -a convert
      - run: convert --version

      - run: apt list --installed | grep gs
      - run: apt list --installed | grep ghostscript

      - run: ghostscript -v
      # - run: |
      #     sudo apt-get --purge remove imagemagick
      #     sudo apt autoremove
      #     sudo apt-get update -qq
      #     sudo apt-get install -y build-essential checkinstall libgs-dev ghostscript
      #     mkdir ~/src
      #     cd ~/src
      #     wget http://www.imagemagick.org/download/releases/ImageMagick-6.7.7-10.tar.xz
      #     tar xf ImageMagick-6.7.7-10.tar.xz
      #     cd ImageMagick-6.7.7-10/
      #     sudo ./configure --with-gslib=yes
      #     sudo make
      #     sudo checkinstall
      #     sudo ldconfig
      # - run: convert --version
