name: 'build-test'

# rebuild any PRs and main branch changes
on:
  pull_request:
  push:
    branches:
      - main
      - wip
      - 'releases/*'

jobs:
  # make sure build/ci work properly
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run build && npm run format && npm run lint && npm run package
      # - run: |
      #     npm run all

  # make sure the action works on a clean machine without building
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./

        with:
          version: 7.0.10-25
          configure_args: '--with-modules'
          # configure_args: '--with-gslib=yes'

      - run: which -a convert
      - run: convert --version
      - run: identify -list configure
      - run: identify -list format
      - run: ghostscript -v

      - run: |-
          pwd
          ls -alh

      - run: env | sort

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.artifactName }}
          path: ${{ env.artifactDir }}
          if-no-files-found: error

      - name: Convert a pdf into png
        run: convert -thumbnail 250x250 -background white -alpha remove -flatten ./test/sample.pdf thumbs.png

  release:
    runs-on: ubuntu-latest

    needs: [compile]

    steps:
      - uses: actions/checkout@v2

      - run: |-
          pwd
          ls -alh

      - run: env | sort

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
